export const Subtitles = () => {
  const sutitlesObject = [ 
    {
      tmdb_ID: "1059128",
      name: "queer",
      videoSrc: "https://mcseguros.com.mx/cineclub/queer-movie.mp4",
      subtitlePath: "/static/subtitles/queer-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Cineclub Forever",
    },
    {
      tmdb_ID: "1232827",
      name: "la-chica-de-la-aguja",
      videoSrc: "https://mcseguros.com.mx/cineclub/the-girl-with-the-needle.mp4",
      subtitlePath: "/static/subtitles/the-girl-with-the-needle-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Cineclub Forever",
    },
    {
      tmdb_ID: "1064213",
      name: "anora",
      videoSrc: "https://mcseguros.com.mx/cineclub/anora.mp4",
      subtitlePath: "/static/subtitles/anora-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Cineclub Forever",
    },
    {
      tmdb_ID: "21575",
      name: "un-profeta",
      videoSrc: "https://mcseguros.com.mx/cineclub/a-prophet-movie.mp4",
      subtitlePath: "/static/subtitles/a-prophet-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Alma",
    },
    {
      tmdb_ID: "823219",
      name: "flow",
      videoSrc: "https://mcseguros.com.mx/cineclub/flow-movie.mp4",
      subtitlePath: "/static/subtitles/flow-subs-esp.vtt",
      ciclo: "Libre",
      propuestaPor: "Alma",
    },
    {
      tmdb_ID: "974950",
      name: "emilia-pérez",
      videoSrc: "https://mcseguros.com.mx/cineclub/emilia-perez.mp4",
      subtitlePath: "/static/subtitles/emilia-perez-subs.vtt",
      ciclo: "Libre",
      propuestaPor: "Cineclub Forever",
    },
    {
      tmdb_ID: "1158915",
      name: "dìdi-(弟弟)",
      videoSrc: "https://mcseguros.com.mx/cineclub/didi.mp4",
      subtitlePath: "/static/subtitles/didi-esp-real.vtt",
      ciclo: "Teens",
      propuestaPor: "Jorge Almora",
    },
    {
      tmdb_ID: "50272",
      name: "somos-lo-que-hay",
      videoSrc: "https://mcseguros.com.mx/cineclub/somos-lo-que-hay.mp4",
      ciclo: "Teens",
      propuestaPor: "Eric",
    },
    {
      tmdb_ID: "42148",
      name: "pixote:-a-lei-do-mais-fraco",
      videoSrc: "https://mcseguros.com.mx/cineclub/pixote.mp4",
      subtitlePath: "/static/subtitles/pixote-esp-translated.vtt",
      ciclo: "Teens",
      propuestaPor: "Victor Portillo",
    },
    {
      tmdb_ID: "23655",
      name: "mundo-rave",
      videoSrc: "https://mcseguros.com.mx/cineclub/groove.mp4",
      subtitlePath: "/static/subtitles/groove-esp.vtt",
      ciclo: "Teens",
      propuestaPor: "Luis Rosales",
    },
    {
      tmdb_ID: "474444",
      name: "les-garçons-sauvages",
      videoSrc: "https://mcseguros.com.mx/cineclub/the-wild-boys.mp4",
      subtitlePath: "/static/subtitles/the-wild-boys-esp.vtt",
      ciclo: "Teens",
      propuestaPor: "Mingo Morales",
    },
  ];

  return sutitlesObject;
};
